export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", currency: "AFN", symbol: "؋" },
  { code: "AL", name: "Albania", currency: "ALL", symbol: "L" },
  { code: "DZ", name: "Algeria", currency: "DZD", symbol: "د.ج" },
  { code: "AD", name: "Andorra", currency: "EUR", symbol: "€" },
  { code: "AO", name: "Angola", currency: "AOA", symbol: "Kz" },
  { code: "AR", name: "Argentina", currency: "ARS", symbol: "$" },
  { code: "AM", name: "Armenia", currency: "AMD", symbol: "֏" },
  { code: "AU", name: "Australia", currency: "AUD", symbol: "A$" },
  { code: "AT", name: "Austria", currency: "EUR", symbol: "€" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", symbol: "₼" },
  { code: "BH", name: "Bahrain", currency: "BHD", symbol: ".د.ب" },
  { code: "BD", name: "Bangladesh", currency: "BDT", symbol: "৳" },
  { code: "BY", name: "Belarus", currency: "BYN", symbol: "Br" },
  { code: "BE", name: "Belgium", currency: "EUR", symbol: "€" },
  { code: "BZ", name: "Belize", currency: "BZD", symbol: "BZ$" },
  { code: "BT", name: "Bhutan", currency: "BTN", symbol: "Nu." },
  { code: "BO", name: "Bolivia", currency: "BOB", symbol: "Bs." },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", symbol: "KM" },
  { code: "BW", name: "Botswana", currency: "BWP", symbol: "P" },
  { code: "BR", name: "Brazil", currency: "BRL", symbol: "R$" },
  { code: "BN", name: "Brunei", currency: "BND", symbol: "B$" },
  { code: "BG", name: "Bulgaria", currency: "BGN", symbol: "лв" },
  { code: "KH", name: "Cambodia", currency: "KHR", symbol: "៛" },
  { code: "CA", name: "Canada", currency: "CAD", symbol: "C$" },
  { code: "CL", name: "Chile", currency: "CLP", symbol: "$" },
  { code: "CN", name: "China", currency: "CNY", symbol: "¥" },
  { code: "CO", name: "Colombia", currency: "COP", symbol: "$" },
  { code: "CR", name: "Costa Rica", currency: "CRC", symbol: "₡" },
  { code: "HR", name: "Croatia", currency: "EUR", symbol: "€" },
  { code: "CU", name: "Cuba", currency: "CUP", symbol: "₱" },
  { code: "CY", name: "Cyprus", currency: "EUR", symbol: "€" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", symbol: "Kč" },
  { code: "DK", name: "Denmark", currency: "DKK", symbol: "kr" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", symbol: "RD$" },
  { code: "EC", name: "Ecuador", currency: "USD", symbol: "$" },
  { code: "EG", name: "Egypt", currency: "EGP", symbol: "£" },
  { code: "SV", name: "El Salvador", currency: "USD", symbol: "$" },
  { code: "EE", name: "Estonia", currency: "EUR", symbol: "€" },
  { code: "ET", name: "Ethiopia", currency: "ETB", symbol: "Br" },
  { code: "FJ", name: "Fiji", currency: "FJD", symbol: "$" },
  { code: "FI", name: "Finland", currency: "EUR", symbol: "€" },
  { code: "FR", name: "France", currency: "EUR", symbol: "€" },
  { code: "GE", name: "Georgia", currency: "GEL", symbol: "₾" },
  { code: "DE", name: "Germany", currency: "EUR", symbol: "€" },
  { code: "GH", name: "Ghana", currency: "GHS", symbol: "GH₵" },
  { code: "GR", name: "Greece", currency: "EUR", symbol: "€" },
  { code: "GT", name: "Guatemala", currency: "GTQ", symbol: "Q" },
  { code: "HN", name: "Honduras", currency: "HNL", symbol: "L" },
  { code: "HK", name: "Hong Kong", currency: "HKD", symbol: "HK$" },
  { code: "HU", name: "Hungary", currency: "HUF", symbol: "Ft" },
  { code: "IS", name: "Iceland", currency: "ISK", symbol: "kr" },
  { code: "IN", name: "India", currency: "INR", symbol: "₹" },
  { code: "ID", name: "Indonesia", currency: "IDR", symbol: "Rp" },
  { code: "IR", name: "Iran", currency: "IRR", symbol: "﷼" },
  { code: "IQ", name: "Iraq", currency: "IQD", symbol: "ع.د" },
  { code: "IE", name: "Ireland", currency: "EUR", symbol: "€" },
  { code: "IL", name: "Israel", currency: "ILS", symbol: "₪" },
  { code: "IT", name: "Italy", currency: "EUR", symbol: "€" },
  { code: "JM", name: "Jamaica", currency: "JMD", symbol: "J$" },
  { code: "JP", name: "Japan", currency: "JPY", symbol: "¥" },
  { code: "JO", name: "Jordan", currency: "JOD", symbol: "د.ا" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", symbol: "₸" },
  { code: "KE", name: "Kenya", currency: "KES", symbol: "KSh" },
  { code: "KR", name: "Korea, South", currency: "KRW", symbol: "₩" },
  { code: "KW", name: "Kuwait", currency: "KWD", symbol: "د.ك" },
  { code: "LV", name: "Latvia", currency: "EUR", symbol: "€" },
  { code: "LB", name: "Lebanon", currency: "LBP", symbol: "ل.ل" },
  { code: "LY", name: "Libya", currency: "LYD", symbol: "ل.د" },
  { code: "LT", name: "Lithuania", currency: "EUR", symbol: "€" },
  { code: "LU", name: "Luxembourg", currency: "EUR", symbol: "€" },
  { code: "MY", name: "Malaysia", currency: "MYR", symbol: "RM" },
  { code: "MV", name: "Maldives", currency: "MVR", symbol: ".ރ" },
  { code: "MT", name: "Malta", currency: "EUR", symbol: "€" },
  { code: "MX", name: "Mexico", currency: "MXN", symbol: "$" },
  { code: "MC", name: "Monaco", currency: "EUR", symbol: "€" },
  { code: "MN", name: "Mongolia", currency: "MNT", symbol: "₮" },
  { code: "ME", name: "Montenegro", currency: "EUR", symbol: "€" },
  { code: "MA", name: "Morocco", currency: "MAD", symbol: "د.م." },
  { code: "MM", name: "Myanmar", currency: "MMK", symbol: "K" },
  { code: "NP", name: "Nepal", currency: "NPR", symbol: "रू" },
  { code: "NL", name: "Netherlands", currency: "EUR", symbol: "€" },
  { code: "NZ", name: "New Zealand", currency: "NZD", symbol: "$" },
  { code: "NG", name: "Nigeria", currency: "NGN", symbol: "₦" },
  { code: "NO", name: "Norway", currency: "NOK", symbol: "kr" },
  { code: "OM", name: "Oman", currency: "OMR", symbol: "ر.ع." },
  { code: "PK", name: "Pakistan", currency: "PKR", symbol: "₨" },
  { code: "PA", name: "Panama", currency: "PAB", symbol: "B/." },
  { code: "PY", name: "Paraguay", currency: "PYG", symbol: "₲" },
  { code: "PE", name: "Peru", currency: "PEN", symbol: "S/." },
  { code: "PH", name: "Philippines", currency: "PHP", symbol: "₱" },
  { code: "PL", name: "Poland", currency: "PLN", symbol: "zł" },
  { code: "PT", name: "Portugal", currency: "EUR", symbol: "€" },
  { code: "QA", name: "Qatar", currency: "QAR", symbol: "ر.ق" },
  { code: "RO", name: "Romania", currency: "RON", symbol: "lei" },
  { code: "RU", name: "Russia", currency: "RUB", symbol: "₽" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", symbol: "ر.س" },
  { code: "RS", name: "Serbia", currency: "RSD", symbol: "din" },
  { code: "SG", name: "Singapore", currency: "SGD", symbol: "S$" },
  { code: "SK", name: "Slovakia", currency: "EUR", symbol: "€" },
  { code: "SI", name: "Slovenia", currency: "EUR", symbol: "€" },
  { code: "ZA", name: "South Africa", currency: "ZAR", symbol: "R" },
  { code: "ES", name: "Spain", currency: "EUR", symbol: "€" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", symbol: "Rs" },
  { code: "SE", name: "Sweden", currency: "SEK", symbol: "kr" },
  { code: "CH", name: "Switzerland", currency: "CHF", symbol: "CHF" },
  { code: "TW", name: "Taiwan", currency: "TWD", symbol: "NT$" },
  { code: "TH", name: "Thailand", currency: "THB", symbol: "฿" },
  { code: "TN", name: "Tunisia", currency: "TND", symbol: "د.ت" },
  { code: "TR", name: "Turkey", currency: "TRY", symbol: "₺" },
  { code: "UA", name: "Ukraine", currency: "UAH", symbol: "₴" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", symbol: "د.إ" },
  { code: "GB", name: "United Kingdom", currency: "GBP", symbol: "£" },
  { code: "US", name: "United States", currency: "USD", symbol: "$" },
  { code: "UY", name: "Uruguay", currency: "UYU", symbol: "$U" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", symbol: "so'm" },
  { code: "VE", name: "Venezuela", currency: "VES", symbol: "Bs.S" },
  { code: "VN", name: "Vietnam", currency: "VND", symbol: "₫" },
  { code: "YE", name: "Yemen", currency: "YER", symbol: "﷼" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", symbol: "Z$" },
].sort((a, b) => a.name.localeCompare(b.name));
