export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", currency: "AFN", symbol: "؋", phoneCode: "93" },
  { code: "AL", name: "Albania", currency: "ALL", symbol: "L", phoneCode: "355" },
  { code: "DZ", name: "Algeria", currency: "DZD", symbol: "د.ج", phoneCode: "213" },
  { code: "AD", name: "Andorra", currency: "EUR", symbol: "€", phoneCode: "376" },
  { code: "AO", name: "Angola", currency: "AOA", symbol: "Kz", phoneCode: "244" },
  { code: "AR", name: "Argentina", currency: "ARS", symbol: "$", phoneCode: "54" },
  { code: "AM", name: "Armenia", currency: "AMD", symbol: "֏", phoneCode: "374" },
  { code: "AU", name: "Australia", currency: "AUD", symbol: "A$", phoneCode: "61" },
  { code: "AT", name: "Austria", currency: "EUR", symbol: "€", phoneCode: "43" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", symbol: "₼", phoneCode: "994" },
  { code: "BH", name: "Bahrain", currency: "BHD", symbol: ".د.ب", phoneCode: "973" },
  { code: "BD", name: "Bangladesh", currency: "BDT", symbol: "৳", phoneCode: "880" },
  { code: "BY", name: "Belarus", currency: "BYN", symbol: "Br", phoneCode: "375" },
  { code: "BE", name: "Belgium", currency: "EUR", symbol: "€", phoneCode: "32" },
  { code: "BZ", name: "Belize", currency: "BZD", symbol: "BZ$", phoneCode: "501" },
  { code: "BT", name: "Bhutan", currency: "BTN", symbol: "Nu.", phoneCode: "975" },
  { code: "BO", name: "Bolivia", currency: "BOB", symbol: "Bs.", phoneCode: "591" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", symbol: "KM", phoneCode: "387" },
  { code: "BW", name: "Botswana", currency: "BWP", symbol: "P", phoneCode: "267" },
  { code: "BR", name: "Brazil", currency: "BRL", symbol: "R$", phoneCode: "55" },
  { code: "BN", name: "Brunei", currency: "BND", symbol: "B$", phoneCode: "673" },
  { code: "BG", name: "Bulgaria", currency: "BGN", symbol: "лв", phoneCode: "359" },
  { code: "KH", name: "Cambodia", currency: "KHR", symbol: "៛", phoneCode: "855" },
  { code: "CA", name: "Canada", currency: "CAD", symbol: "C$", phoneCode: "1" },
  { code: "CL", name: "Chile", currency: "CLP", symbol: "$", phoneCode: "56" },
  { code: "CN", name: "China", currency: "CNY", symbol: "¥", phoneCode: "86" },
  { code: "CO", name: "Colombia", currency: "COP", symbol: "$", phoneCode: "57" },
  { code: "CR", name: "Costa Rica", currency: "CRC", symbol: "₡", phoneCode: "506" },
  { code: "HR", name: "Croatia", currency: "EUR", symbol: "€", phoneCode: "385" },
  { code: "CU", name: "Cuba", currency: "CUP", symbol: "₱", phoneCode: "53" },
  { code: "CY", name: "Cyprus", currency: "EUR", symbol: "€", phoneCode: "357" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", symbol: "Kč", phoneCode: "420" },
  { code: "DK", name: "Denmark", currency: "DKK", symbol: "kr", phoneCode: "45" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", symbol: "RD$", phoneCode: "1-809" },
  { code: "EC", name: "Ecuador", currency: "USD", symbol: "$", phoneCode: "593" },
  { code: "EG", name: "Egypt", currency: "EGP", symbol: "£", phoneCode: "20" },
  { code: "SV", name: "El Salvador", currency: "USD", symbol: "$", phoneCode: "503" },
  { code: "EE", name: "Estonia", currency: "EUR", symbol: "€", phoneCode: "372" },
  { code: "ET", name: "Ethiopia", currency: "ETB", symbol: "Br", phoneCode: "251" },
  { code: "FJ", name: "Fiji", currency: "FJD", symbol: "$", phoneCode: "679" },
  { code: "FI", name: "Finland", currency: "EUR", symbol: "€", phoneCode: "358" },
  { code: "FR", name: "France", currency: "EUR", symbol: "€", phoneCode: "33" },
  { code: "GE", name: "Georgia", currency: "GEL", symbol: "₾", phoneCode: "995" },
  { code: "DE", name: "Germany", currency: "EUR", symbol: "€", phoneCode: "49" },
  { code: "GH", name: "Ghana", currency: "GHS", symbol: "GH₵", phoneCode: "233" },
  { code: "GR", name: "Greece", currency: "EUR", symbol: "€", phoneCode: "30" },
  { code: "GT", name: "Guatemala", currency: "GTQ", symbol: "Q", phoneCode: "502" },
  { code: "HN", name: "Honduras", currency: "HNL", symbol: "L", phoneCode: "504" },
  { code: "HK", name: "Hong Kong", currency: "HKD", symbol: "HK$", phoneCode: "852" },
  { code: "HU", name: "Hungary", currency: "HUF", symbol: "Ft", phoneCode: "36" },
  { code: "IS", name: "Iceland", currency: "ISK", symbol: "kr", phoneCode: "354" },
  { code: "IN", name: "India", currency: "INR", symbol: "₹", phoneCode: "91" },
  { code: "ID", name: "Indonesia", currency: "IDR", symbol: "Rp", phoneCode: "62" },
  { code: "IR", name: "Iran", currency: "IRR", symbol: "﷼", phoneCode: "98" },
  { code: "IQ", name: "Iraq", currency: "IQD", symbol: "ع.د", phoneCode: "964" },
  { code: "IE", name: "Ireland", currency: "EUR", symbol: "€", phoneCode: "353" },
  { code: "IL", name: "Israel", currency: "ILS", symbol: "₪", phoneCode: "972" },
  { code: "IT", name: "Italy", currency: "EUR", symbol: "€", phoneCode: "39" },
  { code: "JM", name: "Jamaica", currency: "JMD", symbol: "J$", phoneCode: "1-876" },
  { code: "JP", name: "Japan", currency: "JPY", symbol: "¥", phoneCode: "81" },
  { code: "JO", name: "Jordan", currency: "JOD", symbol: "د.ا", phoneCode: "962" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", symbol: "₸", phoneCode: "7" },
  { code: "KE", name: "Kenya", currency: "KES", symbol: "KSh", phoneCode: "254" },
  { code: "KR", name: "Korea, South", currency: "KRW", symbol: "₩", phoneCode: "82" },
  { code: "KW", name: "Kuwait", currency: "KWD", symbol: "د.ك", phoneCode: "965" },
  { code: "LV", name: "Latvia", currency: "EUR", symbol: "€", phoneCode: "371" },
  { code: "LB", name: "Lebanon", currency: "LBP", symbol: "ل.ل", phoneCode: "961" },
  { code: "LY", name: "Libya", currency: "LYD", symbol: "ل.د", phoneCode: "218" },
  { code: "LT", name: "Lithuania", currency: "EUR", symbol: "€", phoneCode: "370" },
  { code: "LU", name: "Luxembourg", currency: "EUR", symbol: "€", phoneCode: "352" },
  { code: "MY", name: "Malaysia", currency: "MYR", symbol: "RM", phoneCode: "60" },
  { code: "MV", name: "Maldives", currency: "MVR", symbol: ".ރ", phoneCode: "960" },
  { code: "MT", name: "Malta", currency: "EUR", symbol: "€", phoneCode: "356" },
  { code: "MX", name: "Mexico", currency: "MXN", symbol: "$", phoneCode: "52" },
  { code: "MC", name: "Monaco", currency: "EUR", symbol: "€", phoneCode: "377" },
  { code: "MN", name: "Mongolia", currency: "MNT", symbol: "₮", phoneCode: "976" },
  { code: "ME", name: "Montenegro", currency: "EUR", symbol: "€", phoneCode: "382" },
  { code: "MA", name: "Morocco", currency: "MAD", symbol: "د.م.", phoneCode: "212" },
  { code: "MM", name: "Myanmar", currency: "MMK", symbol: "K", phoneCode: "95" },
  { code: "NP", name: "Nepal", currency: "NPR", symbol: "रू", phoneCode: "977" },
  { code: "NL", name: "Netherlands", currency: "EUR", symbol: "€", phoneCode: "31" },
  { code: "NZ", name: "New Zealand", currency: "NZD", symbol: "$", phoneCode: "64" },
  { code: "NG", name: "Nigeria", currency: "NGN", symbol: "₦", phoneCode: "234" },
  { code: "NO", name: "Norway", currency: "NOK", symbol: "kr", phoneCode: "47" },
  { code: "OM", name: "Oman", currency: "OMR", symbol: "ر.ع.", phoneCode: "968" },
  { code: "PK", name: "Pakistan", currency: "PKR", symbol: "₨", phoneCode: "92" },
  { code: "PA", name: "Panama", currency: "PAB", symbol: "B/.", phoneCode: "507" },
  { code: "PY", name: "Paraguay", currency: "PYG", symbol: "₲", phoneCode: "595" },
  { code: "PE", name: "Peru", currency: "PEN", symbol: "S/.", phoneCode: "51" },
  { code: "PH", name: "Philippines", currency: "PHP", symbol: "₱", phoneCode: "63" },
  { code: "PL", name: "Poland", currency: "PLN", symbol: "zł", phoneCode: "48" },
  { code: "PT", name: "Portugal", currency: "EUR", symbol: "€", phoneCode: "351" },
  { code: "QA", name: "Qatar", currency: "QAR", symbol: "ر.ق", phoneCode: "974" },
  { code: "RO", name: "Romania", currency: "RON", symbol: "lei", phoneCode: "40" },
  { code: "RU", name: "Russia", currency: "RUB", symbol: "₽", phoneCode: "7" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", symbol: "ر.س", phoneCode: "966" },
  { code: "RS", name: "Serbia", currency: "RSD", symbol: "din", phoneCode: "381" },
  { code: "SG", name: "Singapore", currency: "SGD", symbol: "S$", phoneCode: "65" },
  { code: "SK", name: "Slovakia", currency: "EUR", symbol: "€", phoneCode: "421" },
  { code: "SI", name: "Slovenia", currency: "EUR", symbol: "€", phoneCode: "386" },
  { code: "ZA", name: "South Africa", currency: "ZAR", symbol: "R", phoneCode: "27" },
  { code: "ES", name: "Spain", currency: "EUR", symbol: "€", phoneCode: "34" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", symbol: "Rs", phoneCode: "94" },
  { code: "SE", name: "Sweden", currency: "SEK", symbol: "kr", phoneCode: "46" },
  { code: "CH", name: "Switzerland", currency: "CHF", symbol: "CHF", phoneCode: "41" },
  { code: "TW", name: "Taiwan", currency: "TWD", symbol: "NT$", phoneCode: "886" },
  { code: "TH", name: "Thailand", currency: "THB", symbol: "฿", phoneCode: "66" },
  { code: "TN", name: "Tunisia", currency: "TND", symbol: "د.ت", phoneCode: "216" },
  { code: "TR", name: "Turkey", currency: "TRY", symbol: "₺", phoneCode: "90" },
  { code: "UA", name: "Ukraine", currency: "UAH", symbol: "₴", phoneCode: "380" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", symbol: "د.إ", phoneCode: "971" },
  { code: "GB", name: "United Kingdom", currency: "GBP", symbol: "£", phoneCode: "44" },
  { code: "US", name: "United States", currency: "USD", symbol: "$", phoneCode: "1" },
  { code: "UY", name: "Uruguay", currency: "UYU", symbol: "$U", phoneCode: "598" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", symbol: "so'm", phoneCode: "998" },
  { code: "VE", name: "Venezuela", currency: "VES", symbol: "Bs.S", phoneCode: "58" },
  { code: "VN", name: "Vietnam", currency: "VND", symbol: "₫", phoneCode: "84" },
  { code: "YE", name: "Yemen", currency: "YER", symbol: "﷼", phoneCode: "967" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", symbol: "Z$", phoneCode: "263" },
].sort((a, b) => a.name.localeCompare(b.name));
